server:
  port: 8081
# ==============================================
# Zuul Routes config
# ==============================================
zuul:
  routes:
    products:
      path: /api/products/**
      url: http://localhost:8083/products
    oauth:
      path: /oauth/**
      url: http://localhost:8082/auth-service/oauth
    oauthResource:
      path: /oauth-resource/**
      url: http://localhost:8082/auth-service